import { Cta } from "@/components/Sections";
import { site } from "@/lib/site";
import Link from "next/link";

export const metadata = {
  title: "Contatti",
  description: "Contatta Carroattrezzi Cesena MF: telefono 0547 040096, email assistenza@carroattrezzicesenamf.it, sede in Via Cerchia di Sant'Egidio 95.",
};

export default function ContactPage() {
  return <main className="pt-20"><section className="bg-[#10201d] py-20 text-white"><div className="container max-w-4xl"><p className="mb-4 text-sm font-black uppercase tracking-[0.25em] text-lime-200">contatti</p><h1 className="mb-6 text-4xl font-black lg:text-6xl">Contatta il carroattrezzi a Cesena</h1><p className="text-lg leading-8 text-emerald-50/80">Per urgenze chiama direttamente. Per richieste programmate puoi inviare una email con punto di ritiro, destinazione e tipo di veicolo.</p></div></section><section className="py-20"><div className="container grid gap-10 lg:grid-cols-2"><div className="rounded-[2rem] bg-white p-8 shadow-sm"><h2 className="mb-6 text-3xl font-black">Richiedi assistenza</h2><form action={`mailto:${site.email}`} method="post" encType="text/plain" className="space-y-4"><input name="nome" placeholder="Nome e cognome" className="w-full rounded-2xl border border-slate-200 px-5 py-4" /><input name="telefono" placeholder="Telefono" className="w-full rounded-2xl border border-slate-200 px-5 py-4" /><input name="posizione" placeholder="Dove si trova il veicolo?" className="w-full rounded-2xl border border-slate-200 px-5 py-4" /><textarea name="messaggio" placeholder="Descrivi problema, veicolo e destinazione" rows={6} className="w-full rounded-2xl border border-slate-200 px-5 py-4" /><button className="rounded-full bg-[#0f766e] px-8 py-4 font-black text-white">Invia richiesta</button></form></div><div className="rounded-[2rem] bg-emerald-50 p-8"><h2 className="mb-6 text-3xl font-black">Dati utili</h2><div className="space-y-5 text-lg text-slate-700"><p><strong>Telefono:</strong> <Link href={`tel:${site.tel}`} className="text-[#0f766e]">{site.phone}</Link></p><p><strong>Email:</strong> <Link href={`mailto:${site.email}`} className="text-[#0f766e]">{site.email}</Link></p><p><strong>Sede:</strong> {site.address}</p><p><strong>Orari:</strong> assistenza per urgenze stradali 24 ore su 24.</p></div><iframe title="Mappa Cesena" className="mt-8 h-72 w-full rounded-2xl border-0" loading="lazy" src="https://www.google.com/maps?q=Via%20Cerchia%20di%20Sant%27Egidio%2095%2047521%20Cesena%20FC&output=embed" /></div></div></section><Cta /></main>;
}
